import React, { useState, useEffect, useRef } from 'react';
import { BudgetData } from '../types';
import { CURRENCY_SYMBOLS, MONTH_NAMES } from '../constants';
import { jsPDF } from 'jspdf';
import * as XLSX from 'xlsx';
import { Card } from '../components/ui/Card';
import { Download, FileText, Table, Trash2, Save, Moon, Sun, Bell, BellRing, ChevronLeft, ChevronRight, Upload, X, Shield, Globe, DollarSign, Check, Calendar } from 'lucide-react';
import { calculateTotals } from '../utils/calculations';

interface ToolsViewProps {
  data: BudgetData;
  updateData: (d: BudgetData) => void;
  resetData: () => void;
  isDarkMode: boolean;
  toggleTheme: () => void;
  notificationCount: number;
  onToggleNotifications: () => void;
  onBack: () => void;
  initialTab?: 'tools' | 'settings';
}

interface UserProfile {
  name: string;
  email: string;
  joined: number;
}

export const ToolsView: React.FC<ToolsViewProps> = ({ 
  data, 
  updateData, 
  resetData, 
  isDarkMode, 
  toggleTheme, 
  notificationCount, 
  onToggleNotifications, 
  onBack,
  initialTab = 'tools'
}) => {
  const [user, setUser] = useState<UserProfile | null>(null);
  const viewMode = initialTab;
  const fileInputRef = useRef<HTMLInputElement>(null);

  // Settings State
  const [activeSetting, setActiveSetting] = useState<'notifications' | 'security' | 'language' | 'currency' | 'period' | null>(null);
  const [notifSettings, setNotifSettings] = useState({ push: true, email: false, bills: true });
  const [securitySettings, setSecuritySettings] = useState({ biometrics: false });
  const [language, setLanguage] = useState('English');

  useEffect(() => {
    const savedUser = localStorage.getItem('budget_user_session');
    if (savedUser) {
      try {
        setUser(JSON.parse(savedUser));
      } catch (e) {
        console.error('Failed to parse user session');
      }
    }
  }, []);

  // Settings Handlers
  const updateSetting = (field: keyof BudgetData, value: any) => {
    let newData = { ...data, [field]: value };
    if (field === 'currency') {
      newData.currencySymbol = CURRENCY_SYMBOLS[value as string];
    }
    updateData(newData);
  };

  const exportPDF = () => {
    const doc = new jsPDF();
    const totals = calculateTotals(data);
    let y = 20;
    const lineHeight = 7;
    const pageHeight = doc.internal.pageSize.height;
    
    const checkPageBreak = (needed: number) => {
        if (y + needed > pageHeight - 20) {
            doc.addPage();
            y = 20;
        }
    };

    doc.setFontSize(20);
    doc.text(`Budget Report: ${MONTH_NAMES[data.month]} ${data.year}`, 20, y);
    y += 10;
    
    if (user) {
        doc.setFontSize(10);
        doc.text(`Generated by: ${user.name} (${user.email})`, 20, y);
        y += 10;
    }
    
    // Summary
    doc.setFontSize(16);
    doc.text('Summary', 20, y); y += 10;
    doc.setFontSize(11);
    doc.text(`Total Income: ${data.currencySymbol}${totals.totalIncome.toFixed(2)}`, 25, y); y += lineHeight;
    doc.text(`Total Expenses: ${data.currencySymbol}${totals.totalOut.toFixed(2)}`, 25, y); y += lineHeight;
    doc.text(`Remaining: ${data.currencySymbol}${totals.leftToSpend.toFixed(2)}`, 25, y); y += 15;

    // Helper for sections
    const addSection = (title: string, items: any[], formatter: (item: any) => string) => {
        checkPageBreak(20);
        doc.setFontSize(14);
        doc.text(title, 20, y); 
        y += 8;
        doc.setFontSize(10);
        if (items.length === 0) {
             doc.text("- No items -", 25, y);
             y += lineHeight;
        }
        items.forEach(item => {
            checkPageBreak(lineHeight);
            doc.text(formatter(item), 25, y);
            y += lineHeight;
        });
        y += 10;
    };

    addSection('Income', data.income, i => `${i.name}: ${data.currencySymbol}${i.actual} (Plan: ${i.planned})`);
    addSection('Expenses', data.expenses, i => `${i.name}: ${data.currencySymbol}${i.spent} (Budget: ${i.budgeted})`);
    addSection('Bills', data.bills, i => `${i.name}: ${data.currencySymbol}${i.amount} (Due: ${i.dueDate}, ${i.paid ? 'Paid' : 'Unpaid'})`);
    addSection('Debts', data.debts, i => `${i.name}: Bal ${data.currencySymbol}${i.balance} (Pay: ${i.payment})`);
    addSection('Savings', data.savings, i => `${i.name}: ${data.currencySymbol}${i.amount} (Goal: ${i.planned})`);
    addSection('Goals', data.goals, i => `${i.name}: ${data.currencySymbol}${i.current} / ${i.target} (Monthly: ${i.monthly})`);
    addSection('Investments', data.investments, i => `${i.name}: ${data.currencySymbol}${i.amount}`);

    doc.save(`budget_${data.year}_${data.month}.pdf`);
  };

  const exportExcel = () => {
    const wb = XLSX.utils.book_new();
    const totals = calculateTotals(data);
    
    // Summary Sheet
    const summary = [
        ['Budget Report'],
        ['Period', `${MONTH_NAMES[data.month]} ${data.year}`],
        ['User', user ? user.name : 'Guest'],
        ['Date', new Date().toLocaleDateString()],
        [],
        ['Metric', 'Value'],
        ['Total Income', totals.totalIncome],
        ['Total Expenses', totals.totalExpenses],
        ['Total Bills', totals.totalBills],
        ['Total Debt Payments', totals.totalDebts],
        ['Total Savings', totals.totalSavings],
        ['Net Remaining', totals.leftToSpend]
    ];
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(summary), "Summary");

    // Income Sheet
    const incomeData: any[][] = [['Name', 'Planned', 'Actual']];
    data.income.forEach(i => incomeData.push([i.name, i.planned, i.actual]));
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(incomeData), "Income");

    // Expenses Sheet
    const expenseData: any[][] = [['Name', 'Budgeted', 'Spent']];
    data.expenses.forEach(e => expenseData.push([e.name, e.budgeted, e.spent]));
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(expenseData), "Expenses");

    // Bills Sheet
    const billsData: any[][] = [['Name', 'Amount', 'Due Date', 'Paid']];
    data.bills.forEach(b => billsData.push([b.name, b.amount, b.dueDate, b.paid ? 'Yes' : 'No']));
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(billsData), "Bills");

    // Debts Sheet
    const debtData: any[][] = [['Name', 'Balance', 'Monthly Payment', 'Due Date', 'Paid']];
    data.debts.forEach(d => debtData.push([d.name, d.balance, d.payment, d.dueDate || '', d.paid ? 'Yes' : 'No']));
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(debtData), "Debts");
    
    // Savings Sheet
    const savingsData: any[][] = [['Name', 'Planned Goal', 'Current Amount']];
    data.savings.forEach(s => savingsData.push([s.name, s.planned, s.amount]));
    XLSX.utils.book_append_sheet(wb, XLSX.utils.aoa_to_sheet(savingsData), "Savings");

    XLSX.writeFile(wb, `budget_export_${data.year}_${data.month}.xlsx`);
  };

  const exportJSON = () => {
    const dataStr = JSON.stringify(data, null, 2);
    const blob = new Blob([dataStr], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `budget-data-${Date.now()}.json`;
    a.click();
  };

  const handleImportJSON = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (!file) return;

    const reader = new FileReader();
    reader.onload = (e) => {
      try {
        const content = e.target?.result as string;
        const parsedData = JSON.parse(content);
        // Basic validation
        if (parsedData.id && parsedData.period && Array.isArray(parsedData.income)) {
             if (confirm(`Import budget "${MONTH_NAMES[parsedData.month] || 'Unknown'} ${parsedData.year || ''}"? This will overwrite the current view.`)) {
                updateData(parsedData);
                alert('Data imported successfully!');
             }
        } else {
            alert('Invalid file format. Please select a valid BudgetFlow JSON backup.');
        }
      } catch (error) {
        alert('Failed to parse JSON file.');
      }
    };
    reader.readAsText(file);
    event.target.value = ''; // Reset input
  };

  const renderSettingsModal = () => {
    if (!activeSetting) return null;

    let title = '';
    let content = null;

    switch (activeSetting) {
      case 'notifications':
        title = 'Notifications';
        content = (
          <div className="space-y-4">
               <ToggleRow label="Push Notifications" checked={notifSettings.push} onChange={v => setNotifSettings({...notifSettings, push: v})} />
               <ToggleRow label="Email Digest" checked={notifSettings.email} onChange={v => setNotifSettings({...notifSettings, email: v})} />
               <ToggleRow label="Bill Due Alerts" checked={notifSettings.bills} onChange={v => setNotifSettings({...notifSettings, bills: v})} />
               <p className="text-xs text-slate-400 mt-4">You will receive alerts based on your device settings.</p>
          </div>
        );
        break;
      case 'security':
         title = 'Security';
         content = (
           <div className="space-y-4">
              <ToggleRow label="Biometric ID" checked={securitySettings.biometrics} onChange={v => setSecuritySettings({...securitySettings, biometrics: v})} />
              <button className="w-full py-3 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 font-bold text-sm hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors text-left px-4">Change PIN</button>
              <button className="w-full py-3 rounded-xl bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-200 font-bold text-sm hover:bg-slate-200 dark:hover:bg-slate-700 transition-colors text-left px-4">Two-Factor Authentication</button>
           </div>
         );
         break;
      case 'language':
          title = 'Language';
          const langs = ['English', 'Spanish', 'French', 'German', 'Chinese', 'Japanese'];
          content = (
              <div className="space-y-2">
                  {langs.map(l => (
                      <button key={l} onClick={() => { setLanguage(l); setActiveSetting(null); }} className="w-full flex items-center justify-between p-3 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                          <span className={`font-medium ${language === l ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-700 dark:text-slate-200'}`}>{l}</span>
                          {language === l && <Check size={16} className="text-indigo-600 dark:text-indigo-400" />}
                      </button>
                  ))}
              </div>
          );
          break;
      case 'currency':
          title = 'Currency';
          content = (
              <div className="space-y-2 max-h-[60vh] overflow-y-auto pr-1 custom-scrollbar">
                  {Object.keys(CURRENCY_SYMBOLS).map(c => (
                      <button key={c} onClick={() => { updateSetting('currency', c); setActiveSetting(null); }} className="w-full flex items-center justify-between p-3 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                          <div className="flex items-center gap-3">
                              <div className="w-8 h-8 rounded-full bg-slate-200 dark:bg-slate-700 flex items-center justify-center text-slate-600 dark:text-slate-300 font-bold text-xs">
                                  {CURRENCY_SYMBOLS[c]}
                              </div>
                              <span className={`font-medium ${data.currency === c ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-700 dark:text-slate-200'}`}>{c}</span>
                          </div>
                          {data.currency === c && <Check size={16} className="text-indigo-600 dark:text-indigo-400" />}
                      </button>
                  ))}
              </div>
          );
          break;
      case 'period':
          title = 'Default Period';
          const periods = [
            { id: 'weekly', label: 'Weekly' },
            { id: 'biweekly', label: 'Bi-Weekly' },
            { id: 'monthly', label: 'Monthly' },
            { id: 'paycheck', label: 'By Paycheck' }
          ];
          content = (
              <div className="space-y-2">
                  {periods.map(p => (
                      <button key={p.id} onClick={() => { updateSetting('period', p.id); setActiveSetting(null); }} className="w-full flex items-center justify-between p-3 rounded-xl hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                          <span className={`font-medium ${data.period === p.id ? 'text-indigo-600 dark:text-indigo-400' : 'text-slate-700 dark:text-slate-200'}`}>{p.label}</span>
                          {data.period === p.id && <Check size={16} className="text-indigo-600 dark:text-indigo-400" />}
                      </button>
                  ))}
              </div>
          );
          break;
    }

    return (
      <div className="fixed inset-0 z-[100] flex items-center justify-center p-4">
          <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={() => setActiveSetting(null)} />
          <div className="relative bg-white dark:bg-slate-900 w-full max-w-sm rounded-2xl p-6 shadow-2xl animate-in zoom-in-95 duration-200">
              <div className="flex items-center justify-between mb-6">
                  <h3 className="text-lg font-bold text-slate-900 dark:text-white">{title}</h3>
                  <button onClick={() => setActiveSetting(null)} className="p-1 text-slate-400 hover:text-slate-600 dark:hover:text-white rounded-full hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors">
                      <X size={20} />
                  </button>
              </div>
              {content}
          </div>
      </div>
    );
  };

  return (
    <div className="flex flex-col h-full relative">
       {/* Fixed Header */}
       <div className="flex-none pt-6 px-4 pb-4 bg-slate-50/95 dark:bg-slate-900/95 backdrop-blur-xl z-20 border-b border-slate-200 dark:border-white/5 transition-colors duration-300">
            <div className="flex justify-between items-end">
                <div className="flex items-center gap-3">
                    <button onClick={onBack} className="p-2 -ml-2 rounded-full text-slate-500 hover:bg-slate-200 dark:hover:bg-slate-800 transition-colors">
                        <ChevronLeft size={24} />
                    </button>
                    <div>
                        <h2 className="text-xs font-bold text-indigo-600 dark:text-indigo-400 uppercase tracking-wider mb-0.5">
                            {viewMode === 'tools' ? 'Manage Data' : 'Preferences'}
                        </h2>
                        <h1 className="text-2xl font-bold leading-none tracking-tight text-slate-900 dark:text-white">
                            {viewMode === 'tools' ? 'Tools' : 'Settings'}
                        </h1>
                    </div>
                </div>
                
                <div className="pb-1">
                    <button 
                        onClick={onToggleNotifications}
                        className="relative p-1.5 focus:outline-none active:scale-95 transition-transform"
                    >
                        {notificationCount > 0 ? (
                            <>
                                <BellRing size={20} className="text-indigo-600 dark:text-indigo-400" />
                                <span className="absolute top-1 right-1 -mt-0.5 -mr-0.5 w-2.5 h-2.5 bg-red-500 rounded-full border-2 border-slate-50 dark:border-slate-900"></span>
                            </>
                        ) : (
                            <Bell size={20} className="text-slate-400 dark:text-slate-500 hover:text-slate-600 dark:hover:text-slate-300 transition-colors" />
                        )}
                    </button>
                </div>
            </div>
       </div>

      <div className="flex-1 overflow-y-auto hide-scrollbar p-4 space-y-6 pb-24">
      
      {viewMode === 'tools' && (
        <div className="space-y-6 animate-in slide-in-from-right-2 duration-300">
            {/* Export Options */}
            <Card>
                <h3 className="text-sm font-semibold mb-4 text-slate-700 dark:text-slate-300">Export Data</h3>
                <div className="grid grid-cols-1 gap-3">
                    <button onClick={exportPDF} className="flex items-center gap-3 p-3 bg-red-500/10 hover:bg-red-500/20 text-red-500 dark:text-red-400 rounded-lg transition-colors text-left active:scale-[0.99]">
                        <FileText size={20} />
                        <div>
                            <span className="block font-bold text-sm">Export PDF</span>
                            <span className="text-[10px] opacity-70">Download printable report with full details</span>
                        </div>
                        <ChevronRight size={16} className="ml-auto opacity-50" />
                    </button>
                    <button onClick={exportExcel} className="flex items-center gap-3 p-3 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-600 dark:text-emerald-400 rounded-lg transition-colors text-left active:scale-[0.99]">
                        <Table size={20} />
                        <div>
                            <span className="block font-bold text-sm">Export Excel</span>
                            <span className="text-[10px] opacity-70">Spreadsheet (.xlsx) with multiple sheets</span>
                        </div>
                        <ChevronRight size={16} className="ml-auto opacity-50" />
                    </button>
                    <button onClick={exportJSON} className="flex items-center gap-3 p-3 bg-indigo-500/10 hover:bg-indigo-500/20 text-indigo-600 dark:text-indigo-400 rounded-lg transition-colors text-left active:scale-[0.99]">
                        <Save size={20} />
                        <div>
                            <span className="block font-bold text-sm">Save Backup</span>
                            <span className="text-[10px] opacity-70">JSON format for restoring later</span>
                        </div>
                        <ChevronRight size={16} className="ml-auto opacity-50" />
                    </button>
                </div>
            </Card>

            {/* Import Section */}
            <Card>
                <h3 className="text-sm font-semibold mb-4 text-slate-700 dark:text-slate-300">Import Data</h3>
                <input 
                    type="file" 
                    accept=".json" 
                    className="hidden" 
                    ref={fileInputRef} 
                    onChange={handleImportJSON} 
                />
                <button 
                    onClick={() => fileInputRef.current?.click()}
                    className="w-full flex items-center gap-3 p-3 bg-slate-100 dark:bg-slate-800 hover:bg-slate-200 dark:hover:bg-slate-700 text-slate-700 dark:text-slate-200 rounded-lg transition-colors text-left border border-dashed border-slate-300 dark:border-slate-600 active:scale-[0.99]"
                >
                    <Upload size={20} />
                    <div>
                        <span className="block font-bold text-sm">Import JSON Backup</span>
                        <span className="text-[10px] opacity-70">Restore a previously saved budget file</span>
                    </div>
                    <ChevronRight size={16} className="ml-auto opacity-50" />
                </button>
                <p className="text-[10px] text-slate-400 mt-2 px-1">
                    Note: Importing will overwrite the currently active budget period with the data from the file.
                </p>
            </Card>
        </div>
      )}

      {viewMode === 'settings' && (
        <div className="space-y-6 animate-in slide-in-from-left-2 duration-300">
            {/* App Settings */}
            <Card>
                <h3 className="text-sm font-semibold mb-4 text-slate-700 dark:text-slate-300">Appearance</h3>
                <div className="flex items-center justify-between p-3 bg-slate-50 dark:bg-slate-800 rounded-lg border border-slate-200 dark:border-slate-700">
                <div className="flex items-center gap-3">
                    <div className={`p-2 rounded-lg ${isDarkMode ? 'bg-indigo-500/20 text-indigo-400' : 'bg-orange-500/20 text-orange-500'}`}>
                    {isDarkMode ? <Moon size={18} /> : <Sun size={18} />}
                    </div>
                    <span className="font-bold text-sm text-slate-700 dark:text-slate-200">{isDarkMode ? 'Dark Mode' : 'Light Mode'}</span>
                </div>
                <button 
                    onClick={toggleTheme}
                    className={`w-12 h-6 rounded-full p-1 transition-colors duration-300 relative ${isDarkMode ? 'bg-indigo-600' : 'bg-slate-300'}`}
                >
                    <div className={`w-4 h-4 rounded-full bg-white shadow-sm transform transition-transform duration-300 ${isDarkMode ? 'translate-x-6' : 'translate-x-0'}`} />
                </button>
                </div>
            </Card>

            {/* General Settings */}
            <Card>
                <h3 className="text-sm font-semibold mb-4 text-slate-700 dark:text-slate-300">Preferences</h3>
                <div className="space-y-1">
                    <button onClick={() => setActiveSetting('notifications')} className="w-full flex items-center justify-between p-3 hover:bg-slate-50 dark:hover:bg-slate-800/50 rounded-xl transition-colors group">
                        <div className="flex items-center gap-3">
                            <div className="p-2 rounded-lg bg-indigo-500/10 text-indigo-500 group-hover:bg-indigo-500/20 transition-colors">
                                <Bell size={18} />
                            </div>
                            <span className="text-sm font-medium text-slate-700 dark:text-slate-200">Notifications</span>
                        </div>
                        <ChevronRight size={16} className="text-slate-400" />
                    </button>

                    <button onClick={() => setActiveSetting('security')} className="w-full flex items-center justify-between p-3 hover:bg-slate-50 dark:hover:bg-slate-800/50 rounded-xl transition-colors group">
                        <div className="flex items-center gap-3">
                            <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-500 group-hover:bg-emerald-500/20 transition-colors">
                                <Shield size={18} />
                            </div>
                            <span className="text-sm font-medium text-slate-700 dark:text-slate-200">Security</span>
                        </div>
                        <ChevronRight size={16} className="text-slate-400" />
                    </button>

                    <button onClick={() => setActiveSetting('language')} className="w-full flex items-center justify-between p-3 hover:bg-slate-50 dark:hover:bg-slate-800/50 rounded-xl transition-colors group">
                        <div className="flex items-center gap-3">
                            <div className="p-2 rounded-lg bg-blue-500/10 text-blue-500 group-hover:bg-blue-500/20 transition-colors">
                                <Globe size={18} />
                            </div>
                            <div className="flex flex-col items-start">
                                <span className="text-sm font-medium text-slate-700 dark:text-slate-200">Language</span>
                                <span className="text-[10px] text-slate-400">{language}</span>
                            </div>
                        </div>
                        <ChevronRight size={16} className="text-slate-400" />
                    </button>

                    <button onClick={() => setActiveSetting('currency')} className="w-full flex items-center justify-between p-3 hover:bg-slate-50 dark:hover:bg-slate-800/50 rounded-xl transition-colors group">
                        <div className="flex items-center gap-3">
                            <div className="p-2 rounded-lg bg-amber-500/10 text-amber-500 group-hover:bg-amber-500/20 transition-colors">
                                <DollarSign size={18} />
                            </div>
                            <div className="flex flex-col items-start">
                                <span className="text-sm font-medium text-slate-700 dark:text-slate-200">Currency</span>
                                <span className="text-[10px] text-slate-400">{data.currency} ({data.currencySymbol})</span>
                            </div>
                        </div>
                        <ChevronRight size={16} className="text-slate-400" />
                    </button>

                    <button onClick={() => setActiveSetting('period')} className="w-full flex items-center justify-between p-3 hover:bg-slate-50 dark:hover:bg-slate-800/50 rounded-xl transition-colors group">
                        <div className="flex items-center gap-3">
                            <div className="p-2 rounded-lg bg-teal-500/10 text-teal-500 group-hover:bg-teal-500/20 transition-colors">
                                <Calendar size={18} />
                            </div>
                            <div className="flex flex-col items-start">
                                <span className="text-sm font-medium text-slate-700 dark:text-slate-200">Default Period</span>
                                <span className="text-[10px] text-slate-400">
                                    {data.period === 'monthly' ? 'Monthly' : 
                                     data.period === 'weekly' ? 'Weekly' : 
                                     data.period === 'biweekly' ? 'Bi-Weekly' : 'Paycheck'}
                                </span>
                            </div>
                        </div>
                        <ChevronRight size={16} className="text-slate-400" />
                    </button>
                </div>
            </Card>

            {/* Danger Zone */}
            <Card className="border-red-500/20">
                <h3 className="text-sm font-semibold mb-4 text-red-500 dark:text-red-400">Danger Zone</h3>
                <button onClick={() => { if(confirm('Reset all data? This will clear all history and settings.')) resetData() }} className="w-full py-3 rounded-lg bg-red-600 hover:bg-red-700 text-white font-bold flex items-center justify-center gap-2 shadow-lg shadow-red-600/20 active:scale-[0.99]">
                    <Trash2 size={18} /> Reset All Data
                </button>
            </Card>
        </div>
      )}
      
      </div>

      {renderSettingsModal()}
    </div>
  );
};

const ToggleRow = ({ label, checked, onChange }: { label: string, checked: boolean, onChange: (v: boolean) => void }) => (
    <div className="flex items-center justify-between py-2 px-1">
        <span className="text-sm font-medium text-slate-700 dark:text-slate-200">{label}</span>
        <button 
            onClick={() => onChange(!checked)}
            className={`w-11 h-6 rounded-full transition-colors relative ${checked ? 'bg-indigo-600' : 'bg-slate-300 dark:bg-slate-700'}`}
        >
            <div className={`w-4 h-4 rounded-full bg-white shadow-sm absolute top-1 transition-transform ${checked ? 'left-6' : 'left-1'}`} />
        </button>
    </div>
);